language: python
sudo: false

python:
  - 3.5
  - 3.6

install:
  - pip install -U pip setuptools pipenv
  - pipenv install -d --system --skip-lock
  - pip install codecov

script: pytest

after_success:
  - codecov
