openapi: '3.1.0'

servers:
  - url: /api

info:
  title: API
  description: API
  version: '1.0.0'

paths:
  /doc/{doc_id:\d+}:
    post:
      tags: [documents]
      operationId: setDocument
      description: Set document
      parameters:
        - name: doc_id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'swagger.yaml#/components/schemas/Document'
      responses:
        200:
          description: OK
        400:
          description: validation error

components:
  schemas:
    Document:
      type: object
      additionalProperties: false
      properties:
        doc_id:
          type: string
        text:
          type: string
      required:
        - text
