name: Tests

on:
  push:
    branches:
      - master
    tags: [ '*' ]
  pull_request:
    branches:
      - master
      - 0.9.X

jobs:
  isort-mypy-flake8:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          pip install -U pipenv isort mypy flake8 flake8-print
      - name: isort
        run: |
          isort -c aiohttp_apiset tests
      - name: flake8
        run: |
          flake8 aiohttp_apiset tests
      - name: mypy
        run: |
          mypy aiohttp_apiset tests

  tests:
    strategy:
      max-parallel: 7
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.7'
          - '3.9'
          - '3.10'
          - pypy-3.8
          - pypy-3.9
        include:
          - os: ubuntu-latest
            python-version: '3.8'
            coverage: true
          - os: macOS-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.8'
          - os: ubuntu-20.04
            python-version: '3.5'
            deps: >-
              'pytest-aiohttp<1'
              pytest-mock
              'aiohttp-jinja2<1.3'
              jsonschema
              pyyaml
          - os: ubuntu-20.04
            python-version: '3.6'
            deps: >-
              'pytest-aiohttp<1'
              pytest-mock
              aiohttp-jinja2
              jsonschema
              pyyaml

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install hatch
        if: ${{ !matrix.deps }}
        run: |
          pip install -U hatch
      - name: Install dependencies
        if: ${{ matrix.deps }}
        run: |
          pip install ${{ matrix.deps }}
      - name: ruff
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:ruff check aiohttp_apiset tests
      - name: isort
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:isort -c aiohttp_apiset tests
      - name: black
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:black --check --diff aiohttp_apiset tests
      - name: mypy
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:mypy aiohttp_apiset tests
      - name: Tests with coverage
        if: ${{ !matrix.deps }}
        run: |
          hatch run cov
      - name: Tests
        if: ${{ matrix.deps }}
        run: pytest
      - name: coverage.xml
        if: ${{ matrix.coverage }}
        run: |
          hatch run coverage xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
