name: Tests

on: [push]

jobs:
  isort-mypy-flake8:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          pip install -U pipenv isort mypy flake8 flake8-print
          pipenv install -d --skip-lock --system
      - name: isort
        run: |
          isort -c aiohttp_apiset tests
      - name: flake8
        run: |
          flake8 aiohttp_apiset tests
      - name: mypy
        run: |
          mypy aiohttp_apiset tests

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python:
          - version: 3.6
            file: python3.6
            requirements: -d aiohttp
        include:
          - os: ubuntu-latest
            python:
              version: 3.5
              file: python3.5
              requirements: -d aiohttp
          - os: ubuntu-latest
            python:
              version: 3.6
              file: python3.6
              requirements: -d aiohttp==3.7.2
          - os: ubuntu-latest
            python:
              version: 3.7
              file: python3.7
              requirements: -d aiohttp
          - os: ubuntu-latest
            python:
              version: 3.8
              file: python3.8
              requirements: -d aiohttp
          - os: ubuntu-latest
            python:
              version: pypy3
              file: pypy3
              requirements: aiohttp
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.version }}
    - name: Install dependencies
      run: |
        pip install --user pip setuptools
        pip install --user pipenv
        python -m pipenv --python ${{ matrix.python.file }}
        python -m pipenv run pip install -U pip setuptools codecov
        echo "__version__ = 'tests'" > aiohttp_apiset/version.py
        python -m pipenv run pip install -e .
        python -m pipenv install ${{ matrix.python.requirements }} --skip-lock
    - name: Test with pytest
      run: |
        python -m pipenv run pytest --cov=aiohttp_apiset --cov-report=xml
    - name: Upload coverage to Codecov
      if: ${{ matrix.python.version == '3.5' && matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
