name: Tests

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --user pipenv
        pipenv run pip install -U pip setuptools codecov
        echo "__version__ = 'tests'" > aiohttp_apiset/version.py
        pipenv run pip install -e .
        pipenv install -d --skip-lock --system
    - name: Test with pytest
      run: |
        pytest --cov=aiohttp_apiset --cov-report=xml
    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version == '3.5' && matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
